[package]
name = "fovea-derive"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
description = "Derive macros for fovea"
repository = "https://github.com/karhunen-loeve/fovea-derive"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
trybuild = "1"
